services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:v1.76.0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${SERVICES_DIR}/homarr/appdata:/appdata
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homarr.entrypoints=https"
      - "traefik.http.routers.homarr.rule=Host(`${SUB_DOMAIN_HOMARR}.${DOMAIN}`)"
      - "traefik.http.routers.homarr.tls=true"
      - "traefik.http.services.homarr.loadbalancer.server.port=7575"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:7575 || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: internal
    external: true
